import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../config/theme/app_colors.dart';
import '../../../config/theme/app_dimens.dart';
import '../../../core/errors/api_exception.dart';
import '../../../core/utils/formatters.dart';
import '../../../core/widgets/app_card.dart';
import '../../../core/widgets/async_view.dart';
import '../../../core/widgets/common_widgets.dart';
import '../../../data/models/misc.dart';
import '../../providers/providers.dart';

/// `GET /notifications` and `PATCH /notifications/:id/read`.
///
/// VACCINE rows are generated by the daily cron in
/// `backend/src/cron/vaccineCron.js` (7-day, 1-day and missed reminders).
class NotificationsScreen extends ConsumerWidget {
  const NotificationsScreen({super.key});

  Color _colorFor(String type) {
    switch (type.toUpperCase()) {
      case 'VACCINE':
        return AppColors.teal;
      case 'APPOINTMENT':
        return AppColors.primary600;
      default:
        return AppColors.violet;
    }
  }

  IconData _iconFor(String type) {
    switch (type.toUpperCase()) {
      case 'VACCINE':
        return Icons.vaccines_rounded;
      case 'APPOINTMENT':
        return Icons.event_available_rounded;
      default:
        return Icons.campaign_rounded;
    }
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final AsyncValue<List<AppNotification>> notifications = ref.watch(
      notificationsProvider,
    );

    return Scaffold(
      appBar: AppBar(
        title: const Text('Notifications'),
        actions: <Widget>[
          notifications.maybeWhen(
            data: (List<AppNotification> items) {
              final List<AppNotification> unread = items
                  .where((AppNotification n) => !n.isRead)
                  .toList();
              if (unread.isEmpty) return const SizedBox.shrink();
              return TextButton(
                onPressed: () async {
                  try {
                    for (final AppNotification item in unread) {
                      await ref
                          .read(supportRepositoryProvider)
                          .markNotificationRead(item.id);
                    }
                    ref.invalidate(notificationsProvider);
                    if (context.mounted) {
                      Toast.success(context, 'All marked as read');
                    }
                  } on ApiException catch (error) {
                    if (context.mounted) Toast.error(context, error);
                  }
                },
                child: const Text('Mark all read'),
              );
            },
            orElse: () => const SizedBox.shrink(),
          ),
        ],
      ),
      body: AsyncView<List<AppNotification>>(
        value: notifications,
        onRefresh: () => ref.refresh(notificationsProvider.future),
        isEmpty: (List<AppNotification> items) => items.isEmpty,
        emptyIcon: Icons.notifications_none_rounded,
        emptyTitle: 'No notifications',
        emptyMessage:
            'Vaccine reminders and system messages will show up here.',
        builder: (List<AppNotification> items) => ListView.separated(
          physics: const AlwaysScrollableScrollPhysics(),
          padding: AppSpacing.pageBottom,
          itemCount: items.length,
          separatorBuilder: (_, __) => const SizedBox(height: AppSpacing.md),
          itemBuilder: (BuildContext context, int index) {
            final AppNotification item = items[index];
            final Color color = _colorFor(item.type);

            return AppCard(
              borderColor: item.isRead ? null : color.withValues(alpha: 0.45),
              onTap: item.isRead
                  ? null
                  : () async {
                      try {
                        await ref
                            .read(supportRepositoryProvider)
                            .markNotificationRead(item.id);
                        ref.invalidate(notificationsProvider);
                      } on ApiException catch (error) {
                        if (context.mounted) Toast.error(context, error);
                      }
                    },
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Container(
                    width: 38,
                    height: 38,
                    decoration: BoxDecoration(
                      color: color.withValues(alpha: 0.12),
                      borderRadius: AppRadius.smAll,
                    ),
                    child: Icon(_iconFor(item.type), size: 18, color: color),
                  ),
                  const SizedBox(width: AppSpacing.md),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Row(
                          children: <Widget>[
                            Expanded(
                              child: Text(
                                item.title,
                                style: Theme.of(context).textTheme.titleSmall,
                              ),
                            ),
                            if (!item.isRead)
                              Container(
                                width: 8,
                                height: 8,
                                decoration: BoxDecoration(
                                  color: color,
                                  shape: BoxShape.circle,
                                ),
                              ),
                          ],
                        ),
                        const SizedBox(height: 4),
                        Text(
                          item.body,
                          style: Theme.of(context).textTheme.bodyMedium,
                        ),
                        const SizedBox(height: 6),
                        Text(
                          '${item.type} · ${Fmt.relative(item.createdAt)}',
                          style: Theme.of(context).textTheme.bodySmall,
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            );
          },
        ),
      ),
    );
  }
}
